version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.3
workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          base-revision: << pipeline.git.branch >>
          config-path: .circleci/continue-config.yml
          mapping: |
            service/service-a/.* service-a true
            service/service-b/.* service-b true