version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable
parameters:
  service-a:
    type: boolean
    default: false
  service-b:
    type: boolean
    default: false
    
jobs:
  service_build:
    executor: base
    parameters:
      serviceName:
        type: string
    steps:
      - run: echo Building <<parametrs.serviceName>>       
workflows:
  service_build:
    name: build_a
    serviceName: service-a
    when: 
      and:
        - << pipeline.parameters.service-a >>
    
  service_build:
    name: build_b
    serviceName: service-a
    when: 
      and:
        - << pipeline.parameters.service-b >>