version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

parameters:
  service-a:
    type: boolean
    default: false
  service-b:
    type: boolean
    default: false
    
jobs:
  service_build:
    executor: base
    parameters:
      serviceName:
        type: string
    steps:
      - run: echo Building <<parametrs.serviceName>>
       
workflows:
  build_a:
    when: 
      and:
        - << pipeline.parameters.service-a >>
    jobs:
      - service_build:
          serviceName: service-a
  
    
  build_b:
    when: 
      and:
        - << pipeline.parameters.service-b >>
    jobs:
      - service_build:
          serviceName: service-b